#!/usr/bin/with-contenv bash
# shellcheck shell=bash

echo "
───────────────────────────────────────
RAZORFY_DEBUG       = $RAZORFY_DEBUG
RAZORFY_BINDADDRESS = $RAZORFY_BINDADDRESS
RAZORFY_BINDPORT    = $RAZORFY_BINDPORT
RAZORFY_MAXTHREADS  = $RAZORFY_MAXTHREADS
───────────────────────────────────────
"
