#!/bin/bash

printf "
───────────────────────────────────────
RAZORFY_DEBUG      = ${RAZORFY_DEBUG}
RAZORFY_BINDPORT   = ${RAZORFY_BINDPORT}
RAZORFY_MAXTHREADS = ${RAZORFY_MAXTHREADS}
───────────────────────────────────────
"