#!/command/with-contenv bash

echo "
───────────────────────────────────────
RAZORFY_DEBUG      = ${RAZORFY_DEBUG}
RAZORFY_BINDPORT   = ${RAZORFY_BINDPORT}
RAZORFY_MAXTHREADS = ${RAZORFY_MAXTHREADS}
───────────────────────────────────────
"